#!/usr/bin/env node 

const path = require('path');
const applescript = require('applescript');
const tmi = require('tmi.js');
require('dotenv').config({path: path.join(__dirname, '.env')});

const client = new tmi.Client({
  connection: {secure: true},
  identity: {
    username: process.env.TWITCH_NICK,
    password: process.env.TWITCH_TOKEN
  },
  channels: [process.env.TWITCH_CHANNEL]
});

(async function sendUrlToChat() {
  await client.connect();

  const script = 'tell application "Google Chrome" to get URL of active tab of first window';
  applescript.execString(script, async (err, url) => {
    if (err) return process.exit(1);
    await client.say(process.env.TWITCH_CHANNEL, url);
    process.exit();
  });
})();
